# Site settings
title: CAP-Leasing
email: tas@interactify.dk
description: > # this means to ignore newlines until "baseurl:"
    Din leasing partner
url: "http://cap-leading.dk" # the base hostname & protocol for your site - used for feed.xml
twitter_username: cap-leasing
github_username:  interactify

# Build settings
markdown: kramdown