development:
  backend:
    name: netlify-api
    url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: interactify/cap-leasing # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

collections:
  - name: "showroom"
    label: "Showroom"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "post-title"}
      - {label: "Author", name: "author", widget: "string", preview: "author", tagname: "p", class: "post-meta"}
      - {label: "Cover Image", name: "image", widget: "image", tagname: "div", class: "post-img", folder: "img/posts", optional: true}
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd"}
      - {label: "Short Title", name: "short_title", widget: "string", tagname: "h1", class: "blurb-title"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "small muted"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails"}
    meta:
      - {label: "Tags (seperated by comma)", name: "tags", widget: "tags"}