development:
  backend:
    name: netlify-api
    url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: interactify/cap-leasing # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

collections:
  - name: "showroom"
    label: "Showroom"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1", class: "post-title"}
      - {label: "Beskrivelse", name: "beskrivelse", widget: "markdown", tagname: "div", class: "post-bd"}
      - {label: "Førstegangsydelse", name: "foerstegangsydelse", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Månedlig ydelse", name: "maanedlig_ydelse", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Restværdi", name: "restvaerdi", widget: "string", tagname: "p", class: "small muted hidden"}
      
      # Motor
      - {label: "Volumen", name: "volumen", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Cylindre", name: "cylindre", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Antal ventiler", name: "antal_ventiler", widget: "string", tagname: "p", class: "small muted hidden"}
      
      # Økonomi
      - {label: "Tank", name: "tank", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Km/l", name: "kml", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Grøn ejerafgift", name: "groen_ejerafgift", widget: "string", tagname: "p", class: "small muted hidden"}
      
      # Transmission
      - {label: "Gear", name: "gear", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Træk", name: "traek", widget: "string", tagname: "p", class: "small muted hidden"}
      
      
      # Mål
      - {label: "Længde", name: "laengde", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Bredde", name: "bredde", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Højde", name: "hoejde", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Vægt", name: "vaegt", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Påhæng", name: "paahaeng", widget: "string", tagname: "p", class: "small muted hidden"}
      
      # Type
      - {label: "Type", name: "btype", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Første reg", name: "foerstereg", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Kilometer", name: "kilometer", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Brændstof", name: "braendstof", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Farve", name: "farve", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Døre", name: "doere", widget: "string", tagname: "p", class: "small muted hidden"}
      
      # Ydelse
      - {label: "Effekt", name: "effekt", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Moment", name: "moment", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "Topfart", name: "topfart", widget: "string", tagname: "p", class: "small muted hidden"}
      - {label: "0-100 km/t", name: "acc", widget: "string", tagname: "p", class: "small muted hidden"}
      
      - {label: "Billede 1", name: "billede_1", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 2", name: "billede_2", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 3", name: "billede_3", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 4", name: "billede_4", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 5", name: "billede_5", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 6", name: "billede_6", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 7", name: "billede_7", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 8", name: "billede_8", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 9", name: "billede_9", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
      - {label: "Billede 10", name: "billede_10", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails", optional: true}
    meta:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}